# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright 2026 Anton (darkcite)
# getrandom 0.3 on wasm32-unknown-unknown uses crypto.getRandomValues only when this cfg is set.
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
